# Generated by Django 5.2.6 on 2026-04-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='workspaces__owner_i_042630_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='workspaces__industr_989176_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='workspaces__tax_id_4e4b77_idx',
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='primary_color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
