# Generated by Django 5.2.6 on 2026-05-07 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_company_options_alter_workspace_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The workspace this company belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='workspaces.workspace'),
        ),
    ]
