# Generated by Django 5.2.6 on 2026-05-07 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('workspaces', '0003_alter_company_options_company_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company this task belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workspaces.company'),
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The department this task belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workspaces.department'),
        ),
    ]
