# Generated by Django 5.2.6 on 2026-04-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='members',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
